// Generated by CoffeeScript 1.3.3
(function() {
  var currentTime, fromTime;

  LWF.useCanvasRenderer();

  window.enchant.lwf = {
    _env: {
      defaultFrameRate: 60,
      use3D: true
    }
  };

  enchant.Event.LWF_LOADED = 'lwf_loaded';

  enchant.lwf.requestAnimationFrame = (function() {
    return window.requestAnimationFrame || window.webkitRequestAnimationFrame || window.mozRequestAnimationFrame || window.oRequestAnimationFrame || window.msRequestAnimationFrame || function(callback, element) {
      return window.setTimeout(callback, 1000 / 60);
    };
  })();

  currentTime = 0;

  fromTime = 0;

  enchant.lwf.calcTick = function() {
    var tick;
    currentTime = Date.now() / 1000.0;
    tick = currentTime - fromTime;
    fromTime = currentTime;
    return tick;
  };

  enchant.lwf.LWFEntity = enchant.Class.create(enchant.Entity, {
    initialize: function(lwfFileName, lwfPrefix, fps) {
      if (fps == null) {
        fps = enchant.lwf._env.defaultFrameRate;
      }
      enchant.Entity.call(this);
      this.fps = fps;
      this._lwfFileName = lwfFileName;
      this._lwfPrefix = lwfPrefix;
      this._cache = LWF.ResourceCache.get();
      this._stage = document.createElement('canvas');
      this._stage.width = 0;
      this._stage.height = 0;
      this._stage.style.position = 'absolute';
      document.getElementById('enchant-stage').appendChild(this._stage);
      return this._element = this.stage;
    },
    load: function() {
      var _this = this;
      return this._cache.loadLWF({
        lwf: this._lwfFileName,
        prefix: this._lwfPrefix,
        stage: this._stage,
        use3D: enchant.lwf._env.use3D,
        onload: function(lwf) {
          var e;
          _this.lwf = lwf;
          _this.lwf.setFrameRate(_this.fps);
          e = new enchant.Event(enchant.Event.LWF_LOADED);
          e.lwf = lwf;
          _this.dispatchEvent(e);
          return _this.main();
        }
      });
    },
    main: function() {
      var _this = this;
      enchant.lwf.requestAnimationFrame.call(window, function() {
        return _this.main();
      });
      if (this.lwf != null) {
        this.lwf.exec(enchant.lwf.calcTick());
        return this.lwf.render();
      }
    }
  });

}).call(this);
